### ISSUE TITLE
Find discrepancies in Feed

### ISSUE THREAD

**Issue by leifg** [fintech-to-ynab/fintech-to-ynab#107]
I ran fintech-to-ynab for multiple weeks with Monzo. Unfortunately the balance is off. Also unfortunately ynab doesn't really sort by datetime so it's hard to manually compare.

It should be fairly simple to compare the transactions programatically. Is there a rake task to show what is missing?

**Comment by scottrobertson** [comment]
Running the import CLI should add any that are missing. But, i started messing around with this, but be careful as it was just hacked together to help me with foreign transactions amounts that had been changed since they were first charged.

https://github.com/fintech-to-ynab/fintech-to-ynab/blob/master/app/services/import/monzo.rb#L19-L71

**Comment by leifg** [comment]
In the meantime I figured out what's wrong. Hopefully this will help:

If you use your Monzo card for contactless payment on TfL the charges behave a little different. On first enter you will be charged 10 pennies. At the end of the day this transaction is then replaced with the total amount of your days worth trip. So your balance will be off by that amount minus 10 cents.

**Comment by scottrobertson** [comment]
Yeah that makes sense. The TFL stuff is a mess (not Monzo's fault).

The script above would have fixed that for you. It's basically the same situation as when foreign transactions have their GBP amounts update once the transaction settles.
