### ISSUE TITLE
Error 500 When Using Starling

### ISSUE THREAD

**Issue by rj175** [fintech-to-ynab/fintech-to-ynab#89]
Hello,

I setup the fintech-to-ynab a few days ago and it works well (and a massive thank you for this!), but I now notice when a transaction comes in from Starling I'm getting a 500 internal server error from YNAB:

```
2018-07-26T08:45:01.487538+00:00 heroku[router]: at=info method=POST path="/starling" host=###########.herokuapp.com request_id=d0c7d99f-1882-41ef-be32-a9573537b9c1 fwd="52.18.238.42" dyno=web.1 connect=1ms service=409ms status=500 bytes=189 protocol=https
2018-07-26T08:45:01.482362+00:00 app[web.1]: [d0c7d99f-1882-41ef-be32-a9573537b9c1] ETHON: performed EASY effective_url=https://api.youneedabudget.com/v1/budgets/###########/transactions response_code=400 return_code=ok total_time=0.398665
2018-07-26T08:45:01.483013+00:00 app[web.1]: [d0c7d99f-1882-41ef-be32-a9573537b9c1] Completed 500 Internal Server Error in 401ms
2018-07-26T08:45:01.483455+00:00 app[web.1]: [d0c7d99f-1882-41ef-be32-a9573537b9c1]   
2018-07-26T08:45:01.483477+00:00 app[web.1]: [d0c7d99f-1882-41ef-be32-a9573537b9c1] YNAB::ApiError (Bad Request):
2018-07-26T08:45:01.483478+00:00 app[web.1]: [d0c7d99f-1882-41ef-be32-a9573537b9c1]   
2018-07-26T08:45:01.483505+00:00 app[web.1]: [d0c7d99f-1882-41ef-be32-a9573537b9c1] app/services/ynab/client.rb:26:in `create_transaction'
2018-07-26T08:45:01.483507+00:00 app[web.1]: [d0c7d99f-1882-41ef-be32-a9573537b9c1] app/services/ynab/transaction_creator.rb:14:in `create'
2018-07-26T08:45:01.483508+00:00 app[web.1]: [d0c7d99f-1882-41ef-be32-a9573537b9c1] app/controllers/starling_controller.rb:55:in `receive'
```

Not sure if I have just setup the webhook wrong within Starling, any help would be great.

**Comment by scottrobertson** [comment]
Hey

I am going to need to add more logging and debugging so i can see exactly what is going on. I will push that now, then you will have to update your app and wait for another error :)

**Comment by scottrobertson** [comment]
Ok, i have pushed extra logging.

**Comment by rj175** [comment]
Hey, thanks for the quick reply. Sorry if this sounds like a really simple question, but, how do I update my Heroku app? I clicked the 'Deploy to Heroku' button on github when I first set it up

Cheers

**Comment by scottrobertson** [comment]
It's a pretty annoying thing to do to be honest, i don't know why they have made it so complex.

But basically, you need to fork this repo, and then setup Github Deployments inside the app settings on heroku (go to the Deploy tab). 

We are trying to work out a clean way to document this in #68

**Comment by RJacksonm1** [comment]
I'm having the same problem with Monzo -> YNAB transactions, with my recently set up instance. My first transaction after setting fintech-to-ynab up worked (July 23rd), but every transaction since has failed. I wonder if something's changed on YNAB's side?

I adjusted the extra logging on my instance to dump the YNAB api's response:

```patch
  def create_transaction(id: nil, payee_id: nil, payee_name: nil, amount: nil, cleared: nil, date: nil, memo: nil, flag: nil)
    client.transactions.create_transaction(selected_budget_id, {
      transaction: {
        account_id: selected_account_id,
        date: date.to_s,
        amount: amount,
        payee_id: payee_id,
        payee_name: payee_name,
        cleared: cleared ? "Cleared" : 'Uncleared',
        memo: memo,
        flag_color: flag,
        import_id: id
      }
    }).data.transaction
  rescue => e
    Rails.logger.error('YNAB::Client.create_transaction failure')
+    Rails.logger.error(e.response_body)
    Rails.logger.error(e)
    false
  end
```

and the YNAB API is giving me

```
...
E, [2018-07-26T12:34:42.289234 #5] ERROR -- : {"error":{"id":"400","name":"bad_request","detail":"{\"import_id\":[\"A transaction with the same import_id already exists on the account.\"]}"}}
...
```

----

Digging through the code, `import_id` is the `id` given to `YNAB::Client::create_transaction`

https://github.com/fintech-to-ynab/fintech-to-ynab/blob/8c608ea57f802844343e168dfd1d66d18c58d71d/app/services/ynab/client.rb#L25-L38

Which is the first 36 characters of the `id` given to `YNAB::TransactionCreator::create`

https://github.com/fintech-to-ynab/fintech-to-ynab/blob/8c608ea57f802844343e168dfd1d66d18c58d71d/app/services/ynab/transaction_creator.rb#L13-L22

However, `id` is never passed into `YNAB::TransactionCreator::create`

https://github.com/fintech-to-ynab/fintech-to-ynab/blob/751e6e64eb698aa409d66fa1103ca431cd867fdf/app/controllers/monzo_controller.rb#L32-L40

https://github.com/fintech-to-ynab/fintech-to-ynab/blob/8c608ea57f802844343e168dfd1d66d18c58d71d/app/controllers/starling_controller.rb#L45-L53

So the `import_id` for all transactions is `nil`, hence YNAB's API error about duplicate import IDs

**Comment by scottrobertson** [comment]
Hmmm, i wonder if those were lost in a bad merge somewhere. I will get them added back in.

**Comment by scottrobertson** [comment]
Ok, pushed a fix for that.

And yet another reason i hate the whole "fork" thing, you will now how to do this to update: https://help.github.com/articles/syncing-a-fork/

**Comment by scottrobertson** [comment]
And thank you @RJacksonm1 for debugging that.

**Comment by RJacksonm1** [comment]
@scottrobertson No worries, thanks for the fantastic tool!

**Comment by scottrobertson** [comment]
Going to close this, as i think it's fixed now 👍 let me know if it's not.

**Comment by rj175** [comment]
@scottrobertson Seems fine for me! Been moving money between accounts and the transactions are coming though (Surprised I haven't had a call from the bank yet questioning my activity!). Cheers for the quick fix :)

I also got the whole forking the repo thing done, I see what you mean, why is it so complicated!!
